export const REPOSITORIES = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  PASSWORD_RESET_REPOSITORY: 'PASSWORD_RESET_REPOSITORY',
  CLASS_SESSION_REPOSITORY: 'CLASS_SESSION_REPOSITORY',
  STRIKE_REPOSITORY: 'STRIKE_REPOSITORY',
  NOTIFICATION_REPOSITORY: 'NOTIFICATION_REPOSITORY',
  DAILY_CHALLENGE_REPOSITORY: 'DAILY_CHALLENGE_REPOSITORY',
  ACADEMY_REPOSITORY: 'ACADEMY_REPOSITORY',
};

export const COOKIES_NAME = {
  tokenAuth: 'tknAcct',
};
